application: rank-es
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /
  script: rank_es.app

- url: /instant
  script: rank_es.app
  
- url: /submitted
  script: rank_es.app
  
- url: /submittederror
  script: rank_es.app
  
- url: /rss
  script: rank_es.app

- url: /populate_rss
  script: rank_es.app
  login: admin
  
- url: /tasks/feed_bot
  script: feed_bot.app
  
- url: /styles
  static_dir: styles
  
- url: /images
  static_dir: images
  
  
- url: /feedbot
  script: feedbot.app
  login: admin